/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as DoneRouteImport } from './routes/done'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as ApplyKindRouteImport } from './routes/apply.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyKindRoute = ApplyKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => ApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/consult': typeof ConsultRoute
  '/done': typeof DoneRoute
  '/guide': typeof GuideRoute
  '/proposal': typeof ProposalRoute
  '/search': typeof SearchRoute
  '/apply/$kind': typeof ApplyKindRoute
  '/apply/': typeof ApplyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRoute
  '/done': typeof DoneRoute
  '/guide': typeof GuideRoute
  '/proposal': typeof ProposalRoute
  '/search': typeof SearchRoute
  '/apply/$kind': typeof ApplyKindRoute
  '/apply': typeof ApplyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRouteWithChildren
  '/consult': typeof ConsultRoute
  '/done': typeof DoneRoute
  '/guide': typeof GuideRoute
  '/proposal': typeof ProposalRoute
  '/search': typeof SearchRoute
  '/apply/$kind': typeof ApplyKindRoute
  '/apply/': typeof ApplyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/consult'
    | '/done'
    | '/guide'
    | '/proposal'
    | '/search'
    | '/apply/$kind'
    | '/apply/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consult'
    | '/done'
    | '/guide'
    | '/proposal'
    | '/search'
    | '/apply/$kind'
    | '/apply'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/consult'
    | '/done'
    | '/guide'
    | '/proposal'
    | '/search'
    | '/apply/$kind'
    | '/apply/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  ConsultRoute: typeof ConsultRoute
  DoneRoute: typeof DoneRoute
  GuideRoute: typeof GuideRoute
  ProposalRoute: typeof ProposalRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/$kind': {
      id: '/apply/$kind'
      path: '/$kind'
      fullPath: '/apply/$kind'
      preLoaderRoute: typeof ApplyKindRouteImport
      parentRoute: typeof ApplyRoute
    }
  }
}

interface ApplyRouteChildren {
  ApplyKindRoute: typeof ApplyKindRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyKindRoute: ApplyKindRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRouteWithChildren,
  ConsultRoute: ConsultRoute,
  DoneRoute: DoneRoute,
  GuideRoute: GuideRoute,
  ProposalRoute: ProposalRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
